"use client";

import { useState, useTransition } from "react";
import { Briefing } from "@/lib/briefing/types";
import { Badge, BadgeTone } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const severityToTone: Record<Briefing["concerns"][number]["severity"], BadgeTone> = {
  high: "negative",
  medium: "warning",
  low: "neutral",
};

type Props = {
  storeId: string;
  initialBriefing: Briefing;
  initialSource: "claude" | "mock-no-key" | "mock-fallback";
  initialModelId?: string;
  initialError?: string;
};

export function BriefingView({
  storeId,
  initialBriefing,
  initialSource,
  initialModelId,
  initialError,
}: Props) {
  const [briefing, setBriefing] = useState(initialBriefing);
  const [source, setSource] = useState(initialSource);
  const [modelId, setModelId] = useState(initialModelId);
  const [error, setError] = useState(initialError);
  const [isPending, startTransition] = useTransition();
  const [regenError, setRegenError] = useState<string | null>(null);

  const sourceLabel: Record<
    typeof source,
    { label: string; tone: BadgeTone; explainer?: string }
  > = {
    claude: { label: `Generated by ${modelId ?? "Claude"}`, tone: "accent" },
    "mock-no-key": {
      label: "Deterministic mode · public demo",
      tone: "neutral",
      explainer:
        "The public deploy runs without an API key (standard practice for public demos to avoid key exposure). The same signal pipeline narrates the briefing through a deterministic template. Set ANTHROPIC_API_KEY to switch to live Claude generation.",
    },
    "mock-fallback": {
      label: "Fallback briefing · LLM call failed",
      tone: "negative",
      explainer:
        "The Claude call failed; the deterministic narrator took over so the briefing still ships. See the error tag for details.",
    },
  };
  const meta = sourceLabel[source];

  const onRegenerate = () => {
    setRegenError(null);
    startTransition(async () => {
      try {
        const res = await fetch("/api/briefing", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ storeId }),
        });
        if (!res.ok) {
          const err = await res.json().catch(() => null);
          throw new Error(err?.error ?? `Request failed with status ${res.status}`);
        }
        const data = await res.json();
        setBriefing(data.briefing);
        setSource(data.source);
        setModelId(data.modelId);
        setError(data.error);
      } catch (e) {
        setRegenError(e instanceof Error ? e.message : String(e));
      }
    });
  };

  return (
    <article className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] overflow-hidden">
      <div className="p-6 lg:p-8 border-b border-[var(--color-border)] bg-[var(--color-surface-2)]/30">
        <div className="flex items-start justify-between gap-4 flex-wrap">
          <div className="flex items-center gap-2 flex-wrap">
            <Badge tone={meta.tone}>{meta.label}</Badge>
            {error && (
              <Badge tone="warning" title={error}>
                LLM error · using fallback
              </Badge>
            )}
          </div>
          <Button
            variant="secondary"
            size="sm"
            onClick={onRegenerate}
            disabled={isPending}
          >
            {isPending ? "Regenerating…" : "Regenerate"}
          </Button>
        </div>
        {meta.explainer && (
          <p className="mt-3 text-[11px] text-[var(--color-subtle)] leading-relaxed max-w-2xl">
            {meta.explainer}
          </p>
        )}
        <h2 className="mt-5 text-2xl lg:text-3xl font-semibold tracking-tight leading-tight">
          {briefing.headline}
        </h2>
        <p className="mt-3 text-[var(--color-muted)] leading-relaxed text-base lg:text-[17px]">
          {briefing.summary}
        </p>
        {regenError && (
          <p className="mt-3 text-xs text-[var(--color-negative)]">
            Regenerate failed: {regenError}
          </p>
        )}
      </div>

      <div className="grid lg:grid-cols-2 divide-y lg:divide-y-0 lg:divide-x divide-[var(--color-border)]">
        <Section title="Wins" subtitle={`${briefing.wins.length}`} tone="positive">
          {briefing.wins.length === 0 ? (
            <Empty text="No standout wins yesterday — focus on consistency today." />
          ) : (
            <ul className="flex flex-col gap-3">
              {briefing.wins.map((w, i) => (
                <li
                  key={i}
                  className="rounded-lg border border-[var(--color-positive-soft)]/60 bg-[var(--color-positive-soft)]/15 p-4"
                >
                  <div className="flex items-center justify-between gap-2">
                    <h4 className="font-semibold text-sm text-[var(--color-foreground)]">
                      {w.title}
                    </h4>
                    {w.metric && (
                      <span className="text-[10px] uppercase tracking-wider text-[var(--color-positive)] font-medium">
                        {w.metric}
                      </span>
                    )}
                  </div>
                  <p className="mt-1.5 text-sm text-[var(--color-muted)] leading-relaxed">
                    {w.detail}
                  </p>
                </li>
              ))}
            </ul>
          )}
        </Section>

        <Section title="Concerns" subtitle={`${briefing.concerns.length}`} tone="negative">
          {briefing.concerns.length === 0 ? (
            <Empty text="No concerns surfaced — clean day on the data." />
          ) : (
            <ul className="flex flex-col gap-3">
              {briefing.concerns.map((c, i) => (
                <li
                  key={i}
                  className={cn(
                    "rounded-lg border p-4",
                    c.severity === "high"
                      ? "border-[var(--color-negative-soft)]/60 bg-[var(--color-negative-soft)]/20"
                      : c.severity === "medium"
                        ? "border-[var(--color-warning-soft)]/60 bg-[var(--color-warning-soft)]/20"
                        : "border-[var(--color-border)] bg-[var(--color-surface-2)]/40"
                  )}
                >
                  <div className="flex items-center justify-between gap-2">
                    <h4 className="font-semibold text-sm text-[var(--color-foreground)]">
                      {c.title}
                    </h4>
                    <Badge tone={severityToTone[c.severity]}>{c.severity}</Badge>
                  </div>
                  <p className="mt-1.5 text-sm text-[var(--color-muted)] leading-relaxed">
                    {c.detail}
                  </p>
                </li>
              ))}
            </ul>
          )}
        </Section>
      </div>

      <Section title="Actions for today" subtitle={`${briefing.actions.length}`} tone="accent">
        <ol className="flex flex-col gap-3">
          {briefing.actions.map((a, i) => (
            <li
              key={i}
              className="rounded-lg border border-[var(--color-accent-soft)]/50 bg-[var(--color-accent-soft)]/15 p-4 flex flex-col gap-2"
            >
              <div className="flex items-start justify-between gap-3 flex-wrap">
                <h4 className="font-semibold text-[15px] text-[var(--color-foreground)] tracking-tight">
                  {i + 1}. {a.title}
                </h4>
                <div className="flex items-center gap-2">
                  <Badge tone="accent">{a.owner}</Badge>
                </div>
              </div>
              <p className="text-sm text-[var(--color-muted)] leading-relaxed">
                {a.why}
              </p>
              <p className="text-xs text-[var(--color-subtle)]">
                Estimated impact:{" "}
                <span className="text-[var(--color-foreground)]">{a.estimatedImpact}</span>
              </p>
            </li>
          ))}
        </ol>
      </Section>
    </article>
  );
}

function Section({
  title,
  subtitle,
  tone,
  children,
}: {
  title: string;
  subtitle: string;
  tone: "positive" | "negative" | "accent";
  children: React.ReactNode;
}) {
  const dotCls = {
    positive: "bg-[var(--color-positive)]",
    negative: "bg-[var(--color-negative)]",
    accent: "bg-[var(--color-accent)]",
  }[tone];
  return (
    <section className="p-6 lg:p-7 flex flex-col gap-4">
      <header className="flex items-center justify-between">
        <h3 className="text-xs font-semibold uppercase tracking-widest text-[var(--color-muted)] flex items-center gap-2">
          <span className={cn("inline-block size-1.5 rounded-full", dotCls)} />
          {title}
        </h3>
        <span className="text-[11px] tabular text-[var(--color-subtle)]">{subtitle}</span>
      </header>
      {children}
    </section>
  );
}

function Empty({ text }: { text: string }) {
  return (
    <div className="rounded-lg border border-dashed border-[var(--color-border)] p-6 text-center">
      <p className="text-sm text-[var(--color-subtle)]">{text}</p>
    </div>
  );
}
